language: cpp

os: linux

dist: focal

addons:
  apt:
    packages:
      - g++
      - clang
      - cmake
      - make
      - bison
      - flex
      - ronn
      - fuse3
      - pkg-config
      - binutils-dev
      - libboost-context-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-python-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libboost-thread-dev
      - libevent-dev
      - libdouble-conversion-dev
      - libiberty-dev
      - liblz4-dev
      - liblzma-dev
      - libssl-dev
      - libunwind-dev
      - libdwarf-dev
      - libelf-dev
      - libfmt-dev
      - libfuse3-dev
      - libgoogle-glog-dev
      - libsparsehash-dev

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake -DWITH_TESTS=1 ..

script:
  - make -j$(nproc)
  - make test
