# This is a basic workflow to help you get started with Actions

name: default
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: '0'
        ref: ${{ github.ref }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      continue-on-error: true
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      continue-on-error: true
      
    - name: Compile and extract artifacts from docker container
      run: |
        # This creates the dist folder
        export D_ARCH="arm64v8"
        echo "D_ARCH=${D_ARCH}" >> "${GITHUB_ENV}"
        "./build.sh"
        mkdir -p dist
        cp dwarfs-universal dist

    - name: Set permissions for dist directory
      run: |
        sudo chown -R "$(id -u)":"$(id -g)" dist/
        sudo chmod -R 766 dist/

    - name: Upload artifacts to release
      uses: actions/upload-artifact@v4
      with:
        name: dwarfs
        path: 'dist'

    - name: Compute Short SHA
      id: ssha
      run: |
        echo "ssha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    outputs:
      ssha: ${{ steps.ssha.outputs.ssha }}


  release:
      permissions: write-all
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4
          with:
            name: dwarfs

       #continuous
        - name: Releaser
          uses: softprops/action-gh-release@v2.0.8
          with:
            name: "Continuous ${{ env.D_ARCH }}"
            tag_name: "${{ env.D_ARCH }}"
            prerelease: true
            draft: false
            generate_release_notes: false
            files: |
              *dwarfs*
          continue-on-error: true
